### ISSUE TITLE
Fix broken xrefs in source content

### ISSUE THREAD

**Issue by mojavelinux** [webtide/jetty.website#20]
The migration has uncovered numerous broken xrefs in the source content. These are not something the migration script can fix. In order to preserve these references, they must be fixed manually before the migration is run.

I've attached a CSV file that itemizes the broken xrefs and where they can be found. There are 56 unique references, some of which occur numerous times in the same file.

[broken-xref-report.csv](https://github.com/webtide/jetty.website/files/15017136/broken-xref-report.csv)

I've been able to confirm that these broken references exist in the current documentation. For example, the link to "FastCGI support" in https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-client-http-transport-fcgi leads to nowhere.

**Comment by jmcc0nn3ll** [comment]
@mojavelinux I think they have all been resolved now, when you get the chance could you rerun to doublecheck?

**Comment by mojavelinux** [comment]
Yep, I can confirm that did the trick. I've published the site with the updates. Thanks a lot!
